read_location: "Raw_data" ###the name of the store directory DO NOT INCLUDE / just raw name in case of absolute or small relative do not include final /
Ref_genome_path: References/NC_001526.4.fasta ##provide complete path (relative or absolute) to the Reference genome
Ref_Accession: "NC_001526.4" ##remove version such as .4 in the case of NC_001526.4 > use NC_001526
insert_size: "150"
platform: "ILLUMINA" ##put in all caps
batch: "Test" #OPTIONAL